package: 
  name: projectmaslst
  version: 0.4.0

source:
  git_url: https://github.com/bucricket/projectMASlst2.git
  git_tag: version_0.4.0

  
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 0
  script: 

  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - landsat-util = landsat-util:main
    #
    # Would create an entry point called landsat-util that calls landsat-util.main()
    
    - processlst=processlst.processlst:main
    
requirements:
  build:
    - python 2.7*
    - setuptools
    - libgcc
    - gcc
    - scons 
    - jpeg
#    - geotiff ==1.4.1
    - geotiff
    - zlib
    - hdfeos2 2.19*
    - szip
    - libtiff 
    - xz
    - hdf4

    
  run:
    - python 2.7*
    - numpy
    - pyproj 
    #- gdal <=2.1.3
    - gdal
    - lxml
    - h5py 
    - pydap_urs
    - projectmascorrection
    - pycurl
    - joblib >=0.10.3
    - wget
    - pandas
    - projectmasgetlandsat
    - keyring  9.3.1
    - keyrings.alt 1.2


test:
  # Python imports
  imports:
    - processlst

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  requires:

    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/bucricket/projectMASlst2.git
  license: CCO
  summary: 'prepare LST for the pyDisALEXI ET algorithm'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
