name: processlst
dependencies:
    - python 2.7*
    - numpy
    - pyproj
    - gdal
    - lxml
    - h5py
    - pydap_urs
    - projectmascorrection
    - pycurl
    - joblib >=0.10.3
    - wget
    - pandas
    - keyring  9.3.1
    - keyrings.alt 1.2
    - hdf5
